name = "next-hono-d1-template-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "next-hono-d1-template-db"
database_id = "YOUR_D1_DATABASE_ID_HERE"
migrations_dir = "../../packages/db/drizzle"
